# PaymentService Configuration
spring.application.name=payment-service
server.port=8080

# Database
spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driver-class-name=org.h2.Driver

# [SEC] Hardcoded AWS access key + secret key
aws.access-key-id=AKIAIOSFODNN7EXAMPLE
aws.secret-access-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
aws.region=us-east-1
aws.s3.bucket=payment-receipts-prod

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT
jwt.secret=myHardcodedJwtSecret2024!
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.evalcorp.payment=DEBUG
